version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: tmdb_app_dev
    expose:
      - "9000"
    volumes:
      - .:/var/www
      - ./vendor:/var/www/vendor
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: tmdb_nginx_dev
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - app_network

  mongodb:
    image: mongo:latest
    container_name: tmdb_mongodb_dev
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: tmdb_dev
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: tmdb_redis_dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data: